### ISSUE TITLE
Add basic docs to the README

### ISSUE THREAD

**Issue by alexeyzimarev** [EventStore/esc#39]
We refer to the CLI in the "Getting started" for the cloud but it has zero documentation.

Please put at least _something_ to the README.md file so the customers get an idea how to use the CLI.

**Comment by sigil66** [comment]
@YoEight could you add basic usage examples to do the following:

- configure the CLI
- create a token
- create a network
- create a peering link
- create a cluster

**Comment by YoEight** [comment]
On it @sigil66
