### ISSUE TITLE
ESC CLI output is not valid Json

### ISSUE THREAD

**Issue by TomBalt** [EventStore/esc#45]
Hey,

I was trying to use esc cli tool and can't really use it in automation, since it gives a not valid json output.

Having this behavior it's really difficult to extract values.

**Comment by YoEight** [comment]
Weird, when you run a command, did you use the `--output json` option like this:
```
esc --output json ...
```
?

**Comment by TomBalt** [comment]
Actually it's working.
However, I would expect that "--output" option be available in the help section for each command and that can be put in any place. As now it has a static place - after esc. 

If you ran command **"esc infra networks list --help"** it doesn't actually show that there is an option to use --output: 
esc-infra-networks-list 1.20.12
List networks of an organization, given a project

USAGE:
    esc infra networks list [OPTIONS]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
        --org-id <org-id>            The organization id the networks relate to [default: ]
        --project-id <project-id>    The project id the networks relate to [default: ]

Anyway, since it's working I will close the case. 

Thank you for your help @YoEight

**Comment by YoEight** [comment]
@TomBalt This is a fair critic and I'll see what I can do to make that option available at all level. UX is paramount.

**Comment by YoEight** [comment]
https://github.com/EventStore/esc/issues/46
